#!/usr/bin/bash

# name		vpn_status
# author	paul[dot]blackburn[at]gmail[dot]com
# written	2022_04_05
# purpose	display details about VPN connection (if any)
#		check for:
#		+ network interface tun0
#		+ default gateway IP address
#		+ IP address of nameserver
#		+ connectivity to well known external IP
#		+ network route to well known web site

# updated	Tue  5 Apr 17:18:40 BST 2022

# 2022_04_05	first draft

#usage		vpn_status [alternative-network-interface-name]

# assumptions	Default network interface name for a VPN tunnel will be tun0
#		If a different VPN network interface name is used it can be given on command line

# todo

vpn_nin=tun0   # VPN network_interface_name

# status flags
vpn_nin_flag="down"
gw_flag="down"
ns_flag="down"
eip_flag="down"
e_google_flag="down"

# Is there a network interface name on command line parameter 1?
if [ -z ${1} ]; then
	vpn_nin="tun0"
else
	vpn_nin=${1}
fi

echo "Checking for network interface ${vpn_nin}"

echo ifconfig ${vpn_nin}
ifconfig ${vpn_nin}

if [ $? = 0 ]; then
	vpn_nin_flag="up"
	echo "VPN active on network interface: ${vpn_nin}"
else
	echo "+-----------------------------------------------------+"
	echo "| Network interface ${vpn_nin} not found: VPN is not active |"
	echo "+-----------------------------------------------------+"
	exit 1
fi

echo "Checking default gateway address"

echo "netstat -rn | grep ^0.0.0.0 | head -1 | awk '{print $2}'"
gw=$(netstat -rn | grep ^0.0.0.0 | head -1 | awk '{print $2}')
echo ${gw}

echo "Checking network connectivity to default gateway: ${gw}"

echo "ping -c2 ${gw}"
ping -c2 ${gw}

if [ $? = 0 ]; then
	gw_flag="up"
	echo "connection to default gateway ${gw} is up"
else
	echo "connection to default gateway ${gw} is down"
fi

echo "Checking for nameserver IP address"

echo "grep nameserver /etc/resolv.conf"
grep nameserver /etc/resolv.conf


echo "Checking network connectivity to nameserver(s)"
for ns in $(grep nameserver /etc/resolv.conf | sed -e "s/.* //" ); do
        echo
        echo "ping -c2 ${ns}"
        ping -c2 ${ns}
        if [ $? = 0 ]; then
		ns_flag="up"
                echo "connection to nameserver ${ns} is up"
        else
                echo "connection to nameserver ${ns} is down"
        fi
done

echo "Checking external IP address"

echo "dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'\"' '{ print $2}' "
eip=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}') 
echo ${eip}

echo "Checking network connectivity to well known external IP address"

echo "ping -c2 8.8.8.8"
ping -c2 8.8.8.8
if [ $? = 0 ]; then
	eip_flag="up"
        echo "connection to external IP address 8.8.8.8 is up"
else
        echo "connection to external IP address 8.8.8.8 is down"
fi

echo "Checking network route to well know external website"

echo "/bin/sudo tcptraceroute google.com"
/bin/sudo tcptraceroute google.com

if [ $? = 0 ]; then
	e_google_flag="up"
        echo "connection to google.com is up"
else
        echo "connection to google.com is down"
fi

echo completed

if [ ${vpn_nin_flag} = "up" ]; then
	if [ ${gw_flag} = "up" ]; then
		if [ ${ns_flag} = "up" ]; then
			if [ ${eip_flag} = "up" ]; then
				if [ ${e_google_flag} = "up" ]; then
					echo "+-------------------------------------+"
					echo "| Good news: VPN is up and functional |"
					echo "+-------------------------------------+"
				else
					echo "Unable to connect to google.com" >&2
				fi
			else
				echo "Unable to ping external IP 8.8.8.8" >&2
			fi
		else
			echo "Unable to connect to nameserver" >&2
		fi
	else
		echo "Unable to connect to default gateway" >&2
	fi
else
	echo "VPN network interface is down" >&2
fi
